version = 1

exclude_patterns = ["core/libs/**"]

[[analyzers]]
name = "php"
enabled = true

[[analyzers]]
name = "javascript"
enabled = true

[analyzers.meta]
environment = ["jquery"]
dialect = "flow"


[[transformers]]
name = "standardjs"
enabled = true


